### ISSUE TITLE
Active Agent Test

### ISSUE THREAD

**Issue by supermopf** [TS3Tools/zabbix-teamspeak-template#3]
Hey, i'm pretty new to Zabbix (started today) and really like the template you created.

I imported it and got nearly everything going.
The only problem I have: The active agent tests are not returning anything

My agent does not know about the class "teamspeak", is there some missing configuration in this repo?

-Victor

**Comment by Sebbo94BY** [comment]
Hey @supermopf ,

Do you have any specific error message or can you maybe show some screenshots, what exactly is not working for you?

**Comment by Sebbo94BY** [comment]
Ah, I guess I know, what you mean. I forgot to add and documentate the user parameters. Sorry, my fault.

The pull request #4 should solve your problem. :)

**Comment by supermopf** [comment]
Hey,

just tried it out and i can confirm that #4 fixed this issue.

Have a nice day!
