### ISSUE TITLE
Some objects not populated

### ISSUE THREAD

**Issue by martinmolt** [TS3Tools/zabbix-teamspeak-template#9]
Thanks for your **amazing** work!

One small question: 

There are some objects within zabbix which aren't populated:

- TS3 License Expiry Datetime	
- TS3 License Max. Slots	
- TS3 License Max. Virtual Servers	
- TS3 License Type	
- TS3 Process ID (PID)	
- TS3 Process ID (PID) active

I don't have a license, but it should say so and also say the max. slots etc.
Also I have no clue why the PID is missing.

Both noting dramatic, but I was wondering why they are empy.

Cheers!

**Comment by Sebbo94BY** [comment]
Thanks for your kindful words!

All your mentioned information are provided by the active Zabbix agent configuration: https://github.com/TS3Tools/zabbix-teamspeak-template/tree/main/zabbix_agentd.d

Looks like as you haven't configured this on the host system, where your TeamSpeak server is running on. Am I right?

You can find the installation instructions here: https://github.com/TS3Tools/zabbix-teamspeak-template#user-parameters

**Comment by martinmolt** [comment]
> Looks like as you haven't configured this on the host system, where your TeamSpeak server is running on. Am I right?

I did follow your very good instructions step by step, zabbix agent is running and I also added the config mentioned. 
All items are populated and updating, except the mentioned ones.
TS3-version and clients e.g. are correct, but the above mentioned values are empty.

Also sorry for the late reply ^^

**Comment by Sebbo94BY** [comment]
And the variables are also properly set?

Does the Zabbix agent report any issues?

Are you able to retrieve the values by manually executing the commands from the agent configuration file?

**Comment by Sebbo94BY** [comment]
I'll close this now due to inactivity.
